In [2]:
import pandas as pd
import os
import cv2
from keras.preprocessing.image import img_to_array
import numpy as np
import matplotlib.pyplot as plt
from ExecutionAttributes import ExecutionAttribute
from keras.preprocessing.image import ImageDataGenerator
import numpy as np




Using TensorFlow backend.


In [8]:
path = '/home/amenegotto/dataset/2d/numpy/sem_pre_proc_mini/'
x = np.load(path + 'attributes_train.npy')
y = np.load(path + 'attributes_valid.npy')
z = np.load(path + 'attributes_test.npy')

print(x.shape)
print(y.shape)
print(z.shape)

(800, 20)
(200, 20)
(100, 20)


In [9]:
x

array([[  1. ,  46. , 173. , ...,   4.4,   0.3,   1. ],
       [  1. ,  46. , 173. , ...,   4.4,   0.3,   1. ],
       [  1. ,  46. , 173. , ...,   4.4,   0.3,   1. ],
       ...,
       [  1. ,  68. , 169. , ...,   4.1,   6.1,   0.9],
       [  0. ,  52. , 157. , ...,   4.2,   4.9,   1.1],
       [  0. ,  52. , 157. , ...,   4.2,   4.9,   1.1]])

In [10]:
y

array([[  1. ,  25. , 185. , ...,   4. ,   1. ,   0.8],
       [  1. ,  25. , 185. , ...,   4. ,   1. ,   0.8],
       [  1. ,  25. , 185. , ...,   4. ,   1. ,   0.8],
       ...,
       [  0. ,  70. , 160. , ...,   4.1,   5. ,   0.9],
       [  0. ,  70. , 160. , ...,   4.1,   5. ,   0.9],
       [  0. ,  70. , 160. , ...,   4.1,   5. ,   0.9]])

In [11]:
z

array([[  1. ,  60. , 159. , ...,   4.4,   0.7,   0.8],
       [  1. ,  60. , 159. , ...,   4.4,   0.7,   0.8],
       [  1. ,  60. , 159. , ...,   4.4,   0.7,   0.8],
       ...,
       [  0. ,  70. , 160. , ...,   4.1,   5. ,   0.9],
       [  0. ,  70. , 160. , ...,   4.1,   5. ,   0.9],
       [  0. ,  70. , 160. , ...,   4.1,   5. ,   0.9]])

In [4]:
clinical_data = pd.read_csv('csv/clinical_data.csv')

In [5]:
patient_row = clinical_data[clinical_data["Patient"] == 'foo']

In [6]:
print(patient_row)

Empty DataFrame
Columns: [Source, Patient, Gender, Age at Diagnosis, Height, Weight, Race, Etnicity, Other Malignancy, Family History Cancer Indicator, Family History Cancer  Number Relatives, Alcohol, Hemochromatosis, Hepatitis, Non-Alcoholic Fatty Liver Disease, Other, AFP, Platelets, Prothrombin Time, Albumin, Total Bilirubin, Creatinine, Hcc]
Index: []

[0 rows x 23 columns]


In [7]:
patient_row.empty

True